// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0kG5UFU829S6-dqvH8M0n0FLGHhBA3p4',
    appId: '1:584787993922:web:887a4c55d664503156d4db',
    messagingSenderId: '584787993922',
    projectId: 'vssauthen',
    authDomain: 'vssauthen.firebaseapp.com',
    storageBucket: 'vssauthen.appspot.com',
    measurementId: 'G-BX6176LCSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4h0mF5KawRL8U_qY5mm7wMIOOGcc8eg',
    appId: '1:584787993922:android:9ea999315daab8d356d4db',
    messagingSenderId: '584787993922',
    projectId: 'vssauthen',
    storageBucket: 'vssauthen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4c3x4o6OlfVplUPAH93RJ0SXSIYCnCPo',
    appId: '1:584787993922:ios:5ead27161ab8629656d4db',
    messagingSenderId: '584787993922',
    projectId: 'vssauthen',
    storageBucket: 'vssauthen.appspot.com',
    iosBundleId: 'com.example.vssauthen',
  );
}
